name: .NET Core

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0.100', '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet ${{ matrix.dotnet }}
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test
  
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0.100', '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with ${{ matrix.dotnet }}
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test
  
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0.100', '3.1.100' ]
    name: Dotnet ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with ${{ matrix.dotnet }}
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test
